project:
  type: website
  output-dir: docs
website:
  title: "LidarSpeedTests"
  repo-url: https://github.com/ptompalski/LidarSpeedTests
  repo-actions:
    - source
    - issue
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - text: Results
        menu:
          - href: results_basic.qmd
            text: Basic tasks
          - href: results_tileSizeStorage.qmd
            text: Infulence of tile size and storage type
          - href: results_CPU-RAM.qmd 
            text: CPU and RAM usage
          - href: results_table.qmd
            text: All results (tables)
            
      # - href: data.qmd
      #   text: Data
      # - href: contact.qmd
      #   text: Contact
    right: 
      - icon: github
        aria-label: Github
        href: https://github.com/ptompalski/LidarSpeedTests
        
  # page-footer: 
  #   border: true
  #   center: 
  #     - text: 
        

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

